@startuml
class BlackPlayer <<sealed>> {
    + Alliance : Alliance <<get>>
    + ActivePieces : IEnumerable<Piece> <<get>>
    + Opponent : Player <<get>>
    + BlackPlayer(board:Board, legalMoves:IEnumerable<Move>, opponentsMoves:IEnumerable<Move>)
}
Player <|- BlackPlayer
@enduml
