@startuml
class Pawn <<sealed>> {
    + Pawn(position:int, alliance:Alliance, isFirstMove:bool)
    + <<override>> CalculateLegalMoves(board:Board) : IEnumerable<Move>
    + <<override>> MovePiece(move:Move) : Pawn
}
Piece <|- Pawn
@enduml
